#common makefile header

DIR_INC = /home/pi/Downloads/NewPro/src/include
DIR_BIN = /home/pi/Downloads/NewPro/bin
DIR_LIB = /home/pi/Downloads/NewPro/src/libs


TARGET	= MainControl
BIN_TARGET = $(DIR_BIN)/$(TARGET)

#CROSS_COMPILE = arm-linux-gnueabihf-
CFLAGS = -g -Wall -I$(DIR_INC)

LDFLAGS := -L$(DIR_LIB)/x64

LDFLAGS += -lmsc -lrt -ldl -lpthread -lasound -lwiringPi -lxml2

OBJECTS := $(patsubst %.c,%.o,$(wildcard *.c))

$(BIN_TARGET) : $(OBJECTS)
	$(CROSS_COMPILE)gcc $(CFLAGS) $^ -o $@ $(LDFLAGS)

%.o : %.c
	$(CROSS_COMPILE)gcc -c $(CFLAGS) $< -o $@
clean:
	@rm -f *.o $(BIN_TARGET)

.PHONY:clean
